name: flutter_sodium_example
description: Demonstrates how to use the flutter_sodium plugin.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.0
  convert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sodium:
    path: ../

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
